### ISSUE TITLE
Column width to small?

### ISSUE THREAD

**Issue by weipah** [madeyourday/contao-rocksolid-columns#11]
I set up a 2-1-1 columnset and I think the columns width is rather small and there is much space between them.

First column spanning over two looks okay, but the last two columns seem to small.

![image](https://cloud.githubusercontent.com/assets/1555658/14315416/566c6c22-fbfd-11e5-8107-8862338baf26.png)

Here are the applied styles:
![image](https://cloud.githubusercontent.com/assets/1555658/14315462/af212eac-fbfd-11e5-917d-032957615c3e.png)

I think this comes from .rs-column {margin-right}. 
How is this calculated? Shouldn't that be an optional-setting?

Tried in different browsers and I use latest version of RSC (1.0.6) from ER2 with Contao 1.5.9

**Comment by ausi** [comment]
The extension handles only the CSS classes, the layout of the columns themselves is done via CSS.

You can copy the CSS file [system/modules/rocksolid-columns/assets/css/columns.css](https://github.com/madeyourday/contao-rocksolid-columns/blob/84ee0a9d21019b1c3f2394dfabd20937f06d7e99/assets/css/columns.css), disable “Load column stylesheet” in the layout settings, add the new CSS file to the layout settings and modify it to your needs.

**Comment by weipah** [comment]
@ausi Ok thanks, will do so.
