### ISSUE TITLE
Consider Default value of 'invisible' default-value when creating 'rs_columns_stop'

### ISSUE THREAD

**Issue by jacob418** [madeyourday/contao-rocksolid-columns#12]
When one has set the Content field 'invisible' to default checked, every element is invisible after creation.

When creating a closing wrapper this value is not replicated there, it is set to visible always, indifferent what the default value for 'invisible' field is.

This can lead to bad column set configurations and destructed layouts.

**Comment by ausi** [comment]
Fixed in 476790163ac64f1cd4774b423da83cd695c4794f and 35ca1f9b17c19fd0b774ed3307a85b58fa4b2705
