### ISSUE TITLE
css-grid for rocksolid-columns

### ISSUE THREAD

**Issue by mlwebworker** [madeyourday/contao-rocksolid-columns#17]
Ich würde gerne css-grid bei den rocksolid-columns einsetzen. Dafür fehlen mir aber Klassen beim Spaltenumschlag (ce_rs_columns_start.html5), die sich aus der Gesamtanzahl der Spalten für die jeweilige Breite (Mobile, Tablet, Desktop) ergeben. Ist so etwas machbar? 
Ich hatte schon mal in den Code reingeschaut, habe aber keine Idee wie ich es anstellen soll, dass die mit $media und $columnsTotal generierten Klassen auch im Template ce_rscolumns_start.html5 ausgegeben werden.

**Comment by ausi** [comment]
Im Spaltenumschlag-Template kannst du über `MadeYourDay\RockSolidColumns\Element\ColumnsStart::getColumnsConfiguration($this->arrData)` auf die Klassen-Konfiguration zugreifen. Reicht das für deinen Anwendungsfall aus?

**Comment by mlwebworker** [comment]
Das sollte reichen. Ich werde mal schauen, dass ich mich da als Nicht-Programmierer durchbeisse.

**Comment by mlwebworker** [comment]
Es hat mich zwar ein paar Stunden gekostet um mir zu erarbeiten wie man das Array zerpflückt damit ich an genau die Klassen rankomme die ich brauche. Aber letzten Endes mit Erfolg und einem gewissen Lerneffekt. Vielleicht kannst Du mir noch sagen, ob man das auch eleganter lösen könnte.
Hier mein angepasstes Template ce_rs_columns_start.html
`<?php 
	$config = MadeYourDay\RockSolidColumns\Element\ColumnsStart::getColumnsConfiguration($this->arrData);
	$classes = $config["large"][0][0] . " " . $config["medium"][0][0] . " " . $config["small"][0][0];
?>`
`<div class="rs-columns <?php echo $classes ?> <?php echo $this->class ?>"<?php echo $this->cssID ?><?php if ($this->style): ?> style="<?php echo $this->style ?>"<?php endif ?>>
	<?php if ($this->headline): ?>
		<<?php echo $this->hl ?>><?php echo $this->headline ?></<?php echo $this->hl ?>>
	<?php endif ?>
`

**Comment by ausi** [comment]
Die Anpassung sieht in Ordnung aus 👍

**Comment by mlwebworker** [comment]
Danke. Hast Du grundsätzlich Interesse an den Anpassungen auf css-grid?

**Comment by ausi** [comment]
Bei einer Umstellung der Erweiterung auf CSS-Grid, wäre es sinnvoll auch die Struktur der Spaltenumschläge so umzugestalten, dass die Vorteile von CSS-Grid besser genutzt werden können.

Mit dem aktuellen Aufbau werden wir vermutlich kein CSS-Grid einsetzen.
