### ISSUE TITLE
Backend: Missing indent at second page in article editor

### ISSUE THREAD

**Issue by 463** [madeyourday/contao-rocksolid-columns#20]
![Bug](https://user-images.githubusercontent.com/7769231/139462954-c500db4b-87fb-459a-9f6c-19017992d944.png)

At first page anything works fine.

After moving an element the indents are shown, after reload they are gone again.

**Comment by ausi** [comment]
Does this happen with wrapper elements from Contao itself (like the accordion wrapper) too?
