### ISSUE TITLE
Warning: Missing column start element before column stop element …

### ISSUE THREAD

**Issue by pswerbung** [madeyourday/contao-rocksolid-columns#8]
Rocksolid Columns worked before perfectly, now with Contao 3.5.2. and rocksolid-cokumns Version 1.0.6 it generates a lot of error Code like this. How to fix this?

Warning: Missing column start element before column stop element ID 2112. in system/modules/rocksolid-columns/src/MadeYourDay/Contao/Element/ColumnStop.php on line 39

#0 [internal function]: __error(512, 'Missing column ...', '/home/httpd/vho...', 39, Array)
#1 system/modules/rocksolid-columns/src/MadeYourDay/Contao/Element/ColumnStop.php(39): trigger_error('Missing column ...', 512)
#2 system/modules/core/library/Contao/Controller.php(476): MadeYourDay\Contao\Element\ColumnStop->generate()
#3 system/modules/news/modules/ModuleNews.php(139): Contao\Controller::getContentElement(Object(Contao\ContentModel))
#4 system/modules/core/library/Contao/Template.php(125): Contao\ModuleNews->Contao\{closure}()
#5 system/modules/news/templates/news/news_full.html5(14): Contao\Template->__get('text')
#6 system/modules/core/library/Contao/BaseTemplate.php(88): include('/home/httpd/vho...')
#7 system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#8 system/modules/core/classes/FrontendTemplate.php(46): Contao\Template->parse()
#9 system/modules/news/modules/ModuleNews.php(211): Contao\FrontendTemplate->parse()
#10 system/modules/news/modules/ModuleNewsReader.php(108): Contao\ModuleNews->parseArticle(Object(Contao\Model\Collection))
#11 system/modules/core/modules/Module.php(282): Contao\ModuleNewsReader->compile()
#12 system/modules/news/modules/ModuleNewsReader.php(82): Contao\Module->generate()
#13 system/modules/core/elements/ContentModule.php(59): Contao\ModuleNewsReader->generate()
#14 system/modules/core/library/Contao/Controller.php(476): Contao\ContentModule->generate()
#15 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#16 system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#17 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#18 system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#19 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#20 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#21 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#22 index.php(20): Contao\FrontendIndex->run()
#23 {main}

**Comment by ausi** [comment]
Is there a column start element for the stop element ID 2112? Can you post a backend screenshot of all content elements in that article?

**Comment by pswerbung** [comment]
Yes, here we go: backend, frontend without error-reporting and with reporting enabled …
<img width="778" alt="backend" src="https://cloud.githubusercontent.com/assets/1453011/9323786/7fa17a2c-4584-11e5-8444-3d1060c9cd0e.png">
![error_off](https://cloud.githubusercontent.com/assets/1453011/9323787/7fc10c98-4584-11e5-9909-eb30e6344727.png)
![error_on](https://cloud.githubusercontent.com/assets/1453011/9323788/7fc2aa8a-4584-11e5-8e24-80b24d958251.png)

**Comment by ausi** [comment]
The error message is correct, there is no column start element. You’re using a column wrapper start element (Umschlag Anfang) with a column stop element (Spalte Ende), please use a column wrapper stop element (Umschlag Ende) instead.

**Comment by pswerbung** [comment]
Oha, thanks for helping out!
